web:
  image: nginx:1.11
  ports:
      - "80:80"
  volumns:
    - ./site/dist:/usr/share/nginx/html:ro
    - ./site/conf/nginx.conf:/etc/nginx/nginx.conf
  links:
    - service
service:
  context: ./service
  build: .
  command: node app.js
  ports:
    - "5000:5000"
  volumns:
    - ./service/conf:/app/conf
  links:
    - redis
    - db
  environment:
    - NODE_ENV=production
redis:
  image: redis
db:
  image: mongo